### ISSUE TITLE
Relicense to another Open Source license

### ISSUE THREAD

**Issue by ghost** [jb55/rotate-bits.h#1]
Can you license it under an Open Source license as Public-domain is not recognized in many countries outside the US, particularly in Europe.

Recommended licenses:
- [public-domain-equivalent licenses](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) such as
  - [BSD Zero Clause License](https://choosealicense.com/licenses/0bsd/)
  - [MIT No Attribution](https://choosealicense.com/licenses/mit-0/)
- [MIT License](https://choosealicense.com/licenses/mit/)

**Comment by jb55** [comment]
On Fri, Jun 04, 2021 at 03:34:28AM -0700, arnavyc wrote:
>Can you re-license (or dual-license it) under any other Open Source license as Public-domain is not recognized in many countries outside the US, particularly in Europe.
>
>Recommended licenses:
>- [public-domain-equivalent licenses](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) such as
>  - [BSD Zero Clause License](https://choosealicense.com/licenses/0bsd/)
>  - [MIT No Attribution](https://choosealicense.com/licenses/mit-0/)
>- [MIT License](https://choosealicense.com/licenses/mit/)

if you send a patch with MIT license I will merge it

**Comment by ghost** [comment]
See #2.
